### ISSUE TITLE
Results navigator record sorting

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#162] opened 2021-06-02 23:30 UTC
In Phon 3.3.0, the Results Navigator appear to sort records in alphabetical order, as opposed to numerical order

![Numbers](https://user-images.githubusercontent.com/15111886/120564447-8585d600-c3e5-11eb-9d92-0e3cfa2a6ede.png)

**Comment by ghedlund** [comment] 2021-06-02 23:53
This has always been the case as the type of the values in this column are strings and not numbers.

**Comment by ghedlund** [comment] 2021-06-02 23:54
Closing as a duplicate of #116

**Closed by ghedlund** 2021-06-02 23:54 UTC
